Code & Features Update

diff --git a/l2cu b/l2cu
--- a/l2cu
+++ b/l2cu
@@ -914,7 +914,34 @@ then
 	)
 fi
 
-frobulator.require ${list[@]}
+for requirement in ${list[@]}
+do
+	if [[ -z $(command -v "${requirement} ]]
+	then
+		frobulator.err "Missing" "[ '${requirement}' ]"
+		echo
+
+		frobulator.wrn "Start ${script} as 'root' to install missing application requirements."
+		echo
+
+		exit 1
+	fi
+done
+
+if [[ $(id -u -n) = "root" ]]
+then
+	frobulator.require ${list[@]}
+
+	frobulator.msg "${script} requirements installed."
+	echo
+
+	frobulator.inf "Run ${script} as 'user'" to proceed."
+	echo
+
+	exit
+else
+	:
+fi
 
 list=()
 
