Update ldraw-model-export

diff --git a/ldraw-model-export b/ldraw-model-export
--- a/ldraw-model-export
+++ b/ldraw-model-export
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016
+# Author: Nathanel Titane - nathanel.titane@gmail.com
 
-shopt -s extglob globstar nullglob
-
-# model export #
+# ldraw model export #
 
 black= red= green= yellow= blue= magenta= cyan= white= reset=
 
@@ -21,33 +19,47 @@ then
 	reset=$(tput sgr0)
 fi
 
-version="25-08-2017"
+version="01-01-2020"
 script=$(basename -- "$0")
 
 while (($#))
 do
 	case "$1" in
+		-d|--directory)
+			shift
+			directory="$1"
+			;;
 		-l|--ldr)
-			extension_filter="ldr"
+			extension_option="ldr"
+			extensions_list=(ldr)
 			;;
 		-m|--mpd)
-			extension_filter="mpd"
+			extension_option="mpd"
+			extensions_list=(mpd)
 			;;
 		-3ds)
-			option="3ds"
+			export_option="3ds"
+			export_extension="3ds"
+			export_name="3DS"
 			;;
 		-b|--blender)
-			option="blender"
+			export_option="3ds"
+			export_extension="blend"
+			export_name="Blender"
 			;;
 		-c|--collada)
-			option="collada"
+			export_option="dae"
+			export_extension="dae"
+			export_name="Collada"
 			;;
-		-wf|--wavefront)
-			option="wavefront"
+		-w|--wavefront)
+			export_option="obj"
+			export_extension="obj"
+			export_name="Wavefront"
 			;;
 		-h|--help)
 			echo -e "Usage:"
-			echo -e "./$script [EXTENSION] [OPTION]"
+			echo -e "./$script [EXTENSION] [OPTION] [DIRECTORY]"
 			echo -e ""
 			echo -e "Utility options:"
 			echo -e "-l, --ldr \t\t Selects ldr file format as target."
@@ -55,7 +67,7 @@ do
 			echo -e "-3ds \t\t\t Export 3ds file format only."
 			echo -e "-b, --blender \t\t\t Export blender file format only."
 			echo -e "-c, --collada \t Export collada file format only."
-			echo -e "-wf, --wavefront \t Export wavefront (obj and mtl as zip archive) file format only."
+			echo -e "-w, --wavefront \t Export wavefront (obj and mtl as zip archive) file format only."
 			echo -e "-h, --help \t\t Show help options."
 			echo -e "-v, --version \t Print version."
 			exit
@@ -75,14 +87,19 @@ done
 
 # Test for utility dependencies and requirements
 
-for binary_name in \
-"leocad" \
-"blender" \
-"zip"
+binaries=(
+	leocad
+	blender
+	zip
+)
+
+for binary_name in ${binaries[@]}
 do
 	binary=$(which $binary_name)
 
-	if [[ -z "$binary" ]] # If binary is not found or unspecified
+	# If binary is not found or unspecified
+
+	if [[ -z "$binary" ]]
 	then
 		echo "${yellow}The '$binary_name' binary does not seem to be installed or present on your system.${reset}"
 		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"
@@ -93,7 +110,7 @@ do
 		then
 			# Specify binary location or exit on 'Cancel'
 
-			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || exit
+			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") || exit
 
 			binary="$binary_path/$binary"
 		else
@@ -104,65 +121,34 @@ do
 			exit 1
 		fi
 
-	elif [[ ! -z "$binary" ]] # If binary exists
+	# If binary exists
+
+	elif [[ ! -z "$binary" ]]
 	then
 		echo "${green}'$binary' binary found on system - Continuing...${reset}"
 		echo ""
 
-		leocad=$(which leocad)
-		blender=$(which blender)
-		zip=$(which zip)
+		leocad(){
+			$(which leocad)
+		}
+
+		blender() {
+			$(which blender)
+		}
+
+		zip() {
+			$(which zip)
+		}
 	fi
 
 	sleep 1
 done
 
-if [[ "$extension_filter" == "ldr" ]]
-then
-	extension_filter="ldr"
-	extension="ldr"
+zenity() {
+	/usr/bin/zenity "$@" 2>/dev/null
+}
 
-elif [[ "$extension_filter" == "mpd" ]]
-then
-	extension_filter="mpd"
-	extension="mpd"
-else
-	extension_filter="mpd"
-	extension="mpd"
-
-	echo "${yellow}Defaulting to $extension file format option.${reset}" # Warning when no option set for file type
-	echo""
-fi
-
-if [[ "$option" == "3ds" ]]
-then
-	export_option="-3ds"
-	export_extension="3ds"
-
-elif [[ "$option" == "blender" ]]
-then
-	export_option="-3ds"
-	export_extension="blend"
-
-elif [[ "$option" == "collada" ]]
-then
-	export_option="-dae"
-	export_extension="dae"
-
-elif [[ "$option" == "wavefront" ]]
-then
-	export_option="-obj"
-	export_extension="obj"
-else
-	option="collada"
-	export_option="-dae"
-	export_extension="dae"
-
-	echo "${yellow}Defaulting to $export_extension file export option.${reset}" # Warning when no option set for export type
-	echo ""
-fi
-
-# Generate temporary content
+# Generate temporary file
 
 beautify=$(mktemp /tmp/beautify.XXXXXX)
 trap 'rm -rf "$beautify"' EXIT
@@ -245,152 +231,97 @@ PYTHON
 # Confirm options being used before processing
 
 echo "${cyan}Utility started using the $extension file format option.${reset}"
-echo "${cyan}Utility started using the $option file format option.${reset}"
+echo "${cyan}Utility started using the $export_option file format option.${reset}"
 echo ""
 
-echo "${cyan}Please specify the directory in which you would like the ldraw model files to the be exported to the specified format.${reset}"
+echo "${cyan}Please specify the directory from which you would like the ldraw model files to the be exported.${reset}"
 
 # Specify directory location or exit on 'Cancel'
 
-directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit
+if [[ -z "$directory" ]]
+then
+	directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") || exit
+fi
 
-IFS=$'\n'
-selection=($directory)
-
-for directory in "${selection[@]}"
+for extension in ${extensions_list[@]}
 do
-	cd "$directory" || exit
-
-	for model in "${directory%/}"/**/*."$extension_filter"
+	for model in $(echo $(find ${directory} -iname *.$extension))
 	do
-		IFS='/'
-		read -r -a path <<< "$directory"
+		model_file="${model##*/}"					# Get model file name from path
+		model_file_name="${model_file%.*}"				# Strip extension from model file name
+		model_export_name="${model_file_name:3}"			# Strip first 3 characters from model file name (normally '00-')
+		export_file="${model_export_name}.${export_extension}"
 
-		media_directory=${path[1]}
-		disk_directory=${path[2]}
-		dropbox_directory=${path[3]}
-		lego_directory=${path[4]}
-		models_directory=${path[5]}
-		model_type_directory=${path[6]}
-		model_directory=${path[7]}
+		# Explicit export file types for optimization
+
+		export_file_3ds="${model_export_name}.3ds"
+		export_file_blend="${model_export_name}.blend"
+		export_file_collada="${model_export_name}.dae"
+		export_file_object="${model_export_name}.obj"
+		export_file_material="${model_export_name}.mtl"
+		export_file_archive="${model_export_name}.zip"
 
 		# Define model exports top directory
 
-		exports_directory="/media/Disk/Dropbox/Lego/exports"
+		exports_directory="${model%/*}/exports/"			# Use model directory as root
 
 		# Define model exports UID list location
 
-		uid_list="/media/Disk/Dropbox/Linux/scripts/ldraw/sketchfab/uid-list"
+		uid_list="/media/MEGA/Lego/sketchfab/uid-list"
 
-		# Define file naming variables
+		# Define export routine
 
-		model_file="${model##*/}"					# Get model file name from path
-		model_file_name="${model_file%.*}"			# Strip extension from model file name
-		model_export_name="${model_file_name:3}"	# Strip first 3 characters from model file name (normally '00-')
+		run_leocad () {
 
-		# Define render directory location by model
+			echo "${cyan}Exporting $model to ${export_name} format ("$export_extension")...${reset}"
 
-		export_directory="$exports_directory/$model_type_directory/$model_export_name"
+			leocad "$model" "-$export_option" "$export_file" >> /dev/null
 
-		export_file="$exports_directory/$model_type_directory/$model_export_name/$model_export_name.$export_extension"
-
-		# Explicit file types
-
-		export_file_3ds="$exports_directory/$model_type_directory/$model_export_name/$model_export_name.3ds"
-		export_file_blend="$exports_directory/$model_type_directory/$model_export_name/$model_export_name.blend"
-		export_file_collada="$exports_directory/$model_type_directory/$model_export_name/$model_export_name.dae"
+			wait
+		}
 
 		# Check for the exports directory existence
 
-		if [ ! -d "$exports_directory/$model_type_directory/$model_export_name" ]
+		if [[ ! -d "$exports_directory" ]]
 		then
-			mkdir -p "$exports_directory/$model_type_directory/$model_export_name"
+			mkdir -p "$exports_directory"
 		fi
 
-		# Export 3DS file
+		cd "$exports_directory" || exit
 
-		if [[ "$option" = "3ds" ]]
+		# Export
+
+		if [[ "$export_option" = "3ds" ]] || [[ "$export_option" = "dae" ]] || [[ "$export_option" = "obj" ]]
 		then
-			echo "${cyan}Exporting $model ("$export_extension")...${reset}"
-
-			if [[ ! -d "$export_directory" ]]
-			then
-				mkdir -p "$export_directory"
-			fi
-
-			"$leocad" "$model" "$export_option" "$export_file" >> /dev/null
+			run_leocad
 
 			wait
-		fi
 
-		# Export optimized blend file
-
-		if [[ "$option" = "blender" ]]
-		then
-			echo "${cyan}Exporting $model ("$export_extension")...${reset}"
-
-			# Generate 3DS file
-
-			if [[ ! -d "$export_directory" ]]
+			if [[ "$export_option" = "obj" ]]
 			then
-				mkdir -p "$export_directory"
+				# Archive Wavefront model elements
+
+				zip "$export_file_archive" "$export_file_object" "$export_file_material"
+
+				# Cleanup
+
+				rm -rf {*.obj,*.mtl}
 			fi
 
-			"$leocad" "$model" "$export_option" "$export_file" >> /dev/null
-
-			wait
+		elif [[ "$export_option" = "blender" ]]
+		then
+			run_leocad
 
 			echo "${cyan}Converting $model ("$export_extension")...${reset}"
 
 			# Import 3DS file into blender to create optimized blend file
 
-			"$blender" --background --python "$beautify" "$export_file_3ds" >> /dev/null
+			blender --background --python "$beautify" "$export_file_3ds" >> /dev/null
 
 			# Cleanup
 
 			rm -rf "$export_file_3ds"
 
-			wait
-		fi
-
-		# Export collada file
-
-		if [[ "$option" = "collada" ]]
-		then
-			echo "${cyan}Exporting $model ("$export_extension")...${reset}"
-
-			if [[ ! -d "$export_directory" ]]
-			then
-				mkdir -p "$export_directory"
-			fi
-
-			"$leocad" "$model" "$export_option" "$export_file_collada" >> /dev/null
-
-			wait
-		fi
-
-		# Export wavefront file with materials archive
-
-		if [[ "$option" = "wavefront" ]]
-		then
-					if [[ ! -d "$export_directory" ]]
-			then
-				mkdir -p "$export_directory"
-			fi
-
-			"$leocad" "$model" "$export_option" "$export_file" >> /dev/null
-
-			cd "$export_directory" || exit
-
-			# Archive .obj and respective .mtl files for exported model
-			# when using the wavefront file export option for easy model upload or update
-
-			export_file="${model_export_name}.zip"
-
-			zip "$export_file" {*.obj,*.mtl}
-			rm -rf {*.obj,*.mtl}
-
-			wait
 		fi
 
 		echo ""
@@ -413,18 +344,22 @@ do
 
 			list_uid=""
 
-			if [[ "$model_export_name" == "$model_file_name_list" ]] # If model export name matches list entry
+			# If model export name matches list entry
+
+			if [[ "$model_export_name" == "$model_file_name_list" ]]
 			then
 				model_list_uid_message="${green}Model export name matches UID list entry...${reset}"
 				list_uid="$model_uid"
 				color=$(tput setaf 2) # green
 
-				echo "$model_uid" > "$export_directory/uid"
+				echo "$model_uid" > "$exports_directory/uid"
 
 				break
 			fi
 
 		done < "$uid_list"
+
+		# If UID file does not exist
 
 		if [ -z "$list_uid" ]
 		then
@@ -435,10 +370,10 @@ do
 
 		# Read UID from file
 
-		if [[ -e "$export_directory/uid" ]]
+		if [[ -e "$exports_directory/uid" ]]
 		then
 			model_read_uid_message="${green}UID file exists under model export directory...${reset}"
-			read_uid=$(cat "$export_directory"/uid)
+			read_uid=$(cat "$exports_directory"/uid)
 
 			if [[ -z "$read_uid" ]]
 			then
@@ -447,7 +382,8 @@ do
 			fi
 		fi
 
-		# Verify exported file size and display message accordingly (Free account model upload limit: 50MB)
+		# Verify exported file size and display message accordingly
+		# Free sketchfab account model upload size limit: 50MB
 
 		model_size=$(ls -s --block-size=MB "$export_file" | awk '{print $1}')
 
@@ -461,7 +397,7 @@ do
 
 		elif [[ "$model_size_number" -gt "$model_size_threshold" ]]
 		then
-			model_size_message="${red}Warning: Model file size is above ${model_size_threshold}MB [ $model_size ] - Model cannot be uploaded to free subscription account due to maximum size limitation.${reset}"
+			model_size_message="${red}Warning: Model file size is above ${model_size_threshold}MB [ $model_size ] - Model cannot be uploaded to free subscription account due to model size limit ($model_size_number).${reset}"
 			color=$(tput setaf 1) # red
 		fi
 
