Added dependency and requirements testing on init. Added portabilization options and setup verifications.

diff --git a/make-list b/make-list
--- a/make-list
+++ b/make-list
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014
+# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016
 
 shopt -s extglob globstar nullglob
 
@@ -21,16 +21,18 @@ then
 	reset=$(tput sgr0)
 fi
 
-version="08-05-2016"
+version="26-05-2016"
 script=$(basename -- "$0")
 
 while (($#))
 do
 	case "$1" in
 		-d|--description)
-			mode="description";;
+			mode="description"
+			;;
 		-n|--number)
-			mode="number";;
+			mode="number"
+			;;
 		-h|--help)
 			echo -e "Usage:"
 			echo -e "./$script [OPTION]"
@@ -54,22 +56,112 @@ do
 	shift
 done
 
+# Test for utility dependencies and requirements
+
+for binary in \
+"curl" \
+"wget" \
+"unzip" \
+"zip"
+do
+	binary=$(which $binary)
+
+	if [[ -z "$binary" ]] # If binary is not found or unspecified
+	then
+		echo "${yellow}The '$binary' binary does not seem to be installed or present on your system.${reset}"
+		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"
+
+		read reply
+
+		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
+		then
+			# Specify binary location or exit on 'Cancel'
+
+			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
+
+			binary="$bnary_path/$binary"
+		else
+			echo "${red}Could not specify '$binary' binary installed on system.${reset}"
+			echo "${red}Please install '$binary' using your system's package manager${reset}"
+			echo "${red}and restart this utility when you are done.${reset}"
+			echo ""
+			exit 1
+		fi
+
+	elif [[ ! -z "$binary" ]] # If binary exists
+	then
+		echo "${green}'$binary' binary found on system - Continuing...${reset}"
+		echo ""
+	fi
+
+	sleep 1
+done
+
 # LDraw parts library directory check
 
 if [[ "$(basename $(pwd))" == [lL][dD][rR][aA][wW] ]] && [[ -d "parts" ]]
 then
-	echo "${green}Operating within the LDraw parts library directory. Continuing...${reset}"
+	echo "${green}Operating within the LDraw parts directory. Continuing...${reset}"
 
 	directory="parts"
-else
-	echo "${yellow}LDraw parts library directory not found.${reset}"
+elif [[ "$(basename $(pwd))" != [lL][dD][rR][aA][wW] ]]
+then
+	echo "${yellow}LDraw parts directory not found.${reset}"
 	echo "${yellow}Please specify the LDraw parts library directory location.${reset}"
 
-	browse=$(zenity --file-selection --directory --title="Select the LDraw parts directory location") 2> /dev/null || exit # Specify directory location or exit on 'Cancel'
+	# Specify directory location or exit on 'Cancel'
+
+	browse=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
 
 	cd "$browse" || exit
 
 	directory="$browse/parts"
+else
+	echo "${yellow}LDraw parts directory not found or not setup on this system.${reset}"
+	echo "${yellow}Would you like to have the latest LDraw parts library downloaded and setup on your system?${reset}"
+
+	read reply
+
+	if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
+	then
+		echo "${yellow}Please specify the LDraw parts library directory setup location.${reset}"
+
+		# Specify directory location or exit on 'Cancel'
+
+		setup_directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
+
+		cd "$setup_directory" || exit
+
+		parts_url="http://www.ldraw.org/library/updates/complete.zip"
+		parts_archive=$(basename "$parts_url")
+
+		if [[ ! -z $(which wget) ]]
+		then
+			get_parts=$(wget --show-progress "$parts_url")
+
+		elif [[ ! -z $(which curl ) ]]
+		then
+			get_parts=$(curl -# "$parts_url" > "$parts_archive")
+		else
+			echo "${red}Cannot find suitable utility to fetch the LDraw parts archive - Aborting...${reset}"
+		fi
+
+		echo "${cyan}Downloading...${reset}"
+		echo ""
+		"$get_parts"
+
+		echo "${cyan}Extracting...${reset}"
+		echo ""
+		unzip "$parts_archive"
+
+		cd $setup_directory/[lL][dD][rR][aA][wW]/parts || exit
+	else
+		echo "${red}LDraw parts directory not setup on system - Exiting...${reset}"
+		echo "${cyan}Please visit http://www.ldraw.org to get started.${reset}"
+		echo "${cyan}You may restart this utility to generate the parts list needed for some editors to function${reset}"
+		echo "${cyan}once the LDraw parts library has been downloaded and extracted on your system.${reset}"
+		exit 1
+	fi
 fi
 
 # Parts list verification and backup
diff --git a/model-export b/model-export
--- a/model-export
+++ b/model-export
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014
+# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016
 
 shopt -s extglob globstar nullglob
 
@@ -28,13 +28,17 @@ while (($#))
 do
 	case "$1" in
 		-l|--ldr)
-			extension_filter="ldr";;
+			extension_filter="ldr"
+			;;
 		-m|--mpd)
-			extension_filter="mpd";;
+			extension_filter="mpd"
+			;;
 		-3ds)
-			option="3ds";;
+			option="3ds"
+			;;
 		-wf|--wavefront)
-			option="wavefront";;
+			option="wavefront"
+			;;
 		-h|--help)
 			echo -e "Usage:"
 			echo -e "./$script [EXTENSION] [OPTION]"
@@ -59,6 +63,45 @@ do
 			;;
 		esac
 	shift
+done
+
+# Test for utility dependencies and requirements
+
+for binary in \
+"leocad" \
+"blender"
+do
+	binary=$(which $binary)
+
+	if [[ -z "$binary" ]] # If binary is not found or unspecified
+	then
+		echo "${yellow}The '$binary' binary does not seem to be installed or present on your system.${reset}"
+		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"
+
+		read reply
+
+		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
+		then
+			# Specify binary location or exit on 'Cancel'
+
+			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
+
+			binary="$bnary_path/$binary"
+		else
+			echo "${red}Could not specify '$binary' binary installed on system.${reset}"
+			echo "${red}Please install '$binary' using your system's package manager${reset}"
+			echo "${red}and restart this utility when you are done.${reset}"
+			echo ""
+			exit 1
+		fi
+
+	elif [[ ! -z "$binary" ]] # If binary exists
+	then
+		echo "${green}'$binary' binary found on system - Continuing...${reset}"
+		echo ""
+	fi
+
+	sleep 1
 done
 
 if [[ "$extension_filter" == "ldr" ]]
@@ -95,35 +138,88 @@ else
 	echo ""
 fi
 
+# Generate temporary directory
+
+beautify=$(mktemp /tmp/beautify.XXXXXX)
+trap 'rm -rf "$beautify"' EXIT
+
+# Push python blender beautifier conversion script to temporary file
+
+cat > "$beautify" << 'PYTHON'
+#!/usr/bin/env python3
+
+import os
+import bpy
+context = bpy.context
+
+# prepare scene #
+
+for obj in context.scene.objects:
+	obj.select = True
+
+bpy.ops.object.delete()
+
+# read file path from file #
+
+with open("/tmp/model_file", "r") as file:
+	export_model = file.read().rstrip()
+
+# import #
+
+bpy.ops.import_scene.autodesk_3ds(filepath=export_model)
+
+# join objects #
+
+context.scene.objects.active = context.selected_objects[0]
+bpy.ops.object.join()
+
+# normalize transforms #
+bpy.ops.object.transform_apply(
+	location = True,
+	rotation = True,
+	scale = True
+)
+
+# add smooth shade and edge split modifiers #
+
+bpy.ops.object.shade_smooth()
+bpy.ops.object.modifier_add(
+	type = "EDGE_SPLIT"
+)
+
+# remove doubles #
+
+bpy.ops.object.editmode_toggle()
+bpy.ops.mesh.remove_doubles()
+bpy.ops.mesh.normals_make_consistent(
+	inside = False
+)
+bpy.ops.object.editmode_toggle()
+
+# save #
+
+blend_file = export_model.replace(".3ds",".blend")
+bpy.ops.wm.save_as_mainfile(
+	filepath = blend_file,
+	compress = True
+)
+
+# print output #
+
+print("saved as:", blend_file)
+PYTHON
+
 # Confirm options being used before processing
 
 echo "${cyan}Utility started using the $extension file format option.${reset}"
 echo "${cyan}Utility started using the $option file format option.${reset}"
 echo ""
 
-leocad=$(which leocad) # Define current portable 'leocad' binary location on system
-
-if [[ -z "$leocad" ]] # If 'leocad' binary is not found or unspecified
-then
-	echo "${yellow}The 'leocad' binary does not seem to be present on your system.${reset}"
-	echo "${yellow}Would you like to manually specify its location?${reset}"
-
-	read reply
-
-	if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
-	then
-		leocad=$(zenity --file-selection  --multiple --separator=$'\n' --title="Select binary location") 2> /dev/null || exit # Specify binary location or exit on 'Cancel'
-	else
-		echo "${red}Could not specify or did not find the binary location.${reset}"
-		echo "${red}Cannot continue with the specified binary...${reset}"
-		echo "${red}Please install the package containing the 'leocad' binary on your system and restart this utility.${reset}"
-		exit 1
-	fi
-fi
-
 echo "${cyan}Please specify the directory in which you would like the ldraw model files to the be exported to the specified format.${reset}"
 
-directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit # Specify directory location or exit on 'Cancel'
+# Specify directory location or exit on 'Cancel'
+
+directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
 
 IFS=$'\n'
 selection=($directory)
@@ -150,8 +246,8 @@ do
 		exports_directory="/media/Disk/Dropbox/Lego/exports"
 		uid_list="/media/Disk/Dropbox/Linux/scripts/ldraw/sketchfab/uid-list"
 
-		model_beautifier="/media/Disk/Dropbox/Linux/scripts/ldraw/beautifier.py"
-		model_file_log="/tmp/model_file"
+		model_file_log=$(mktemp /tmp/model_file)
+		trap 'rm -rf "$model_file_log"' EXIT
 
 		model_export="${model##*/}"
 		model_export_name="${model_export%.*}"
@@ -184,7 +280,7 @@ do
 
 		echo "${cyan}Converting $model (blender)...${reset}"
 
-		blender --background --python "$model_beautifier" >> /dev/null
+		blender --background --python "$beautify" >> /dev/null
 
 		wait
 
@@ -274,7 +370,3 @@ do
 		echo ""
 	done
 done
-
-# Clean log file
-
-rm -rf "$model_file_log"
diff --git a/model-render b/model-render
--- a/model-render
+++ b/model-render
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014
+# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016
 
 shopt -s extglob globstar nullglob
 
@@ -21,7 +21,7 @@ then
 	reset=$(tput sgr0)
 fi
 
-version="13-05-2016"
+version="22-05-2016"
 script=$(basename -- "$0")
 
 while (($#))
@@ -65,6 +65,46 @@ do
 	shift
 done
 
+# Test for utility dependencies and requirements
+
+for binary in \
+"LDView" \
+"ldview" \
+"convert"
+do
+	binary=$(which $binary)
+
+	if [[ -z "$binary" ]] # If binary is not found or unspecified
+	then
+		echo "${yellow}The '$binary' binary does not seem to be installed or present on your system.${reset}"
+		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"
+
+		read reply
+
+		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
+		then
+			# Specify binary location or exit on 'Cancel'
+
+			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
+
+			binary="$bnary_path/$binary"
+		else
+			echo "${red}Could not specify '$binary' binary installed on system.${reset}"
+			echo "${red}Please install '$binary' using your system's package manager${reset}"
+			echo "${red}and restart this utility when you are done.${reset}"
+			echo ""
+			exit 1
+		fi
+
+	elif [[ ! -z "$binary" ]] # If binary exists
+	then
+		echo "${green}'$binary' binary found on system - Continuing...${reset}"
+		echo ""
+	fi
+
+	sleep 1
+done
+
 if [[ "$extension_filter" == "ldr" ]]
 then
 	extension_filter="ldr"
@@ -102,7 +142,9 @@ echo "${cyan}Utility started using the $extension file format option.${reset}"
 echo "${cyan}Utility started using the $preset render preset options.${reset}"
 echo ""
 
-directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2&1> /dev/null || exit
+# Specify directory location or exit on 'Cancel'
+
+directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
 
 IFS=$'\n'
 selection=($directory)
@@ -260,9 +302,11 @@ do
 			mkdir -p "$frames_directory"
 		fi
 
+		# Cleanup
+
 		echo "${cyan}Cleaning up...${reset}"
 
-		mv "${renders_directory%/}"/**/*."$render_extension" "$frames_directory" # Cleanup
+		mv "${renders_directory%/}"/**/*."$render_extension" "$frames_directory"
 	fi
 
 	echo "${cyan}Done.${reset}"
diff --git a/model-upload b/model-upload
--- a/model-upload
+++ b/model-upload
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2014
+# Author: Nathanel Titane - nathanel.titane@gmail.com - Copyright 2016
 
 shopt -s extglob globstar nullglob
 
@@ -21,7 +21,7 @@ then
 	reset=$(tput sgr0)
 fi
 
-version="14-05-2016"
+version="28-05-2016"
 script=$(basename -- "$0")
 
 while (($#))
@@ -74,6 +74,47 @@ do
 			;;
 		esac
 	shift
+done
+
+# Test for utility dependencies and requirements
+
+echo "${yellow}Verifying utility requirements...${reset}"
+echo ""
+
+for binary in \
+"curl"
+do
+	binary=$(which $binary)
+
+	if [[ -z "$binary" ]] # If binary is not found or unspecified
+	then
+		echo "${yellow}The '$binary' binary does not seem to be installed or present on your system.${reset}"
+		echo "${yellow}Would you like to specify its location manually? [ Yes | No ]${reset}"
+
+		read reply
+
+		if [[ "$reply" = [yY] || "$reply" = [yY][eE][sS] ]]
+		then
+			# Specify binary location or exit on 'Cancel'
+
+			binary_path=$(zenity --file-selection  --multiple --separator=$'\n' --title="Please specify binary location") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
+
+			binary="$bnary_path/$binary"
+		else
+			echo "${red}Could not specify '$binary' binary installed on system.${reset}"
+			echo "${red}Please install '$binary' using your system's package manager${reset}"
+			echo "${red}and restart this utility when you are done.${reset}"
+			echo ""
+			exit 1
+		fi
+
+	elif [[ ! -z "$binary" ]] # If binary exists
+	then
+		echo "${green}'$binary' binary found on system - Continuing...${reset}"
+		echo ""
+	fi
+
+	sleep 1
 done
 
 if [[ "$option" == "3ds" ]]
@@ -134,18 +175,33 @@ echo "${cyan}Utility started using the $extension file format option.${reset}"
 echo "${cyan}Utility started using the $setup_option setup options.${reset}"
 echo ""
 
-# Generate temporary directory
+# Generate temporary return file for server IDs
 
-temporary_file=( )
-id_file="$(mktemp -t sketchfab-return_XXXXXXXXX)"
+temporary_file=()
+id_file=$(mktemp -t sketchfab-id-file.XXXXXX)
 temporary_file+=("$id_file")
 
 # Define cleanup routine
 
 cleanup() {
-rm "${temporary_file[@]}"
+	rm "${temporary_file[@]}"
 }
+
 trap cleanup EXIT
+
+parse_input () {
+	while true
+	do
+		read input
+
+		if [[ -z $input ]]
+		then
+			echo "${yellow}Warning: Empty value. Please try again...${reset}"
+		else
+			break
+		fi
+	done
+}
 
 # Define upload routine
 
@@ -195,16 +251,81 @@ about () {
 				"${api_server_url}" > "${id_file}"
 }
 
-uid_list="./sketchfab/uid-list"
+# Verify work environment requirements
 
-token_file="./sketchfab/token"
+sketchfab_directory="$(pwd)/sketchfab"
+
+token_url="https://sketchfab.com/settings/password"
+token_file="$sketchfab_directory/token"
 token=$(cat "$token_file")
+
+uid_list="$sketchfab_directory/uid-list"
+
+
+if [[ ! -d "$sketchfab_directory" ]]
+then
+	mkdir "$sketchfab_directory"
+else
+	echo "${green}Sketchfab work directory exists - Continuing...${reset}"
+
+	if [[ ! -e "$token_file" ]]
+	then
+		echo "${yellow}Token file not found.${reset}"
+		echo "${yellow}Please input your API token from the Sketchfab settings page under 'Password & API'.${reset}"
+		echo "${yellow}Please use copy + paste to prevent errors during input.${reset}"
+		echo ""
+
+		sleep 1
+
+		echo "${cyan}Opening settings page:${reset} $token_url"
+		echo ""
+
+		sleep 1
+
+		xdg-open "$token_url" > /dev/null
+		touch "$token_file"
+		parse_input
+		token_input="$?"
+
+		echo "$token_input" > $token_file
+	else
+		echo "${green}Token file exists - Continuing...${reset}"
+		echo "${green}Token...:${reset} $token"
+		echo ""
+	fi
+
+	if [[ ! -e "$uid_list" ]]
+	then
+		echo "${yellow}UIDs list file not found - Creating.${reset}"
+		echo ""
+
+		touch "$uid_list"
+	else
+		echo "${green}UIDs list file file exists - Continuing...${reset}"
+
+		if [[-s "$uid_list" ]]
+		then
+			echo "${green}UIDs list file is populated.${reset}"
+			echo "${green}Entries...:${reset} $(wc -l $uid_list | awk '{print $1}')"
+		else
+			: # pass
+		fi
+	fi
+fi
 
 # Define setup defaults
 
-description_default="This model has been created by Nathanel Titane. </br> For more information, please visit </br> http://www.nathaneltitane.blogspot.com </br> or e-mail me at </br> nathanel.titane@gmail.com"
-tags_default="3d 3ds 3dsmax armogyres armor armored armoredcore armoredknights armors arms armsframe assault battle battleplatforms blender cad cataphract cataphracts combat core design fortresses frame frames gear ghost ghostintheshell gundam heavy heavygear in knights labors ldd ldraw ldview lego leocad lpub macross mech mecha mechanical mechanicalminions micro micropowerarmors microveritechs minions mlcad mobile mobileassaultframes mobilefortresses mobilesuit mobilesuits mobilethrusterframes moc nathanel nathaneltitane orbital orbitalframes platforms pod pods power powerarmor powerarmors reframe shell skeletal skeletalassaultpods suit suits the thruster titane transformer transformers variablefighter veritech veritechs"
+# Format description using HTML line break to prevent words cutting off on  website description panel
 
+full_name="Nathanel Titane"
+website_url="http://www.nathaneltitane.blogspot.com"
+email_address="nathanel.titane@gmail.com"
+
+description_default="This model has been created by $full_name. </br> For more information, please visit </br> $website_url </br> or e-mail me at </br> $email_address"
+
+# Maximum allowed number of tags: 42
+
+tags_default="3d armogyres armoredcore armoredknights armsframe battleplatforms blender cad cataphract design fortresses frames ghostintheshell gundam heavygear labors ldd ldraw ldview lego leocad lpub macross mecha mechanicalminions micropowerarmors microveritechs mlcad mobileassaultframes mobilefortresses mobilesuits mobilethrusterframes moc nathaneltitane nathanel titane orbitalframes powerarmors skeletalassaultpods transformers variablefighters veritechs"
 
 if [[ "$setting_option" = "about" ]]
 then
@@ -268,7 +389,9 @@ then
 
 	done < "$uid_list"
 else
-	directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || exit
+	# Specify directory location or exit on 'Cancel'
+
+	directory=$(zenity --file-selection  --multiple --directory --separator=$'\n' --title="Select a Directory") 2> /dev/null || echo "" && echo "${yellow}Cancel button pressed. Aborting...${reset}" && echo "" && sleep 3 && exit
 
 	IFS=$'\n'
 	selection=($directory)
